# Generated by Django 4.2.1 on 2023-05-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_reportimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='report'),
        ),
    ]
